// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "3e82005b-a395-4be6-b242-b90fc78c6d71");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1554433552);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1554433672);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1554433072);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1554433312);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1554433192);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1554433432);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1554433043);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9633efa3-12d5-45af-b796-bcaad37ba67a}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1554411600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1554433087537");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1554434906537");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1554433052401");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1554436652401");
user_pref("browser.search.region", "UA");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1554433047");
user_pref("browser.slowStartup.averageTime", 4266);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190328071059");
user_pref("browser.startup.homepage_override.mstone", "66.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1554433050038");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "4c6ba17f0f76475e927599c640d35424");
user_pref("extensions.blocklist.lastModified", "Wed, 03 Apr 2019 14:31:00 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1554433554);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190328071059");
user_pref("extensions.lastAppVersion", "66.0.2");
user_pref("extensions.lastPlatformVersion", "66.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{9a9c3e0e-9079-4cc2-bfde-b43912c48d98}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"82be6932-211d-4d6e-b06e-da399525317b\",\"screenshots@mozilla.org\":\"9392ec15-0288-471e-b572-9358196d1a8a\",\"webcompat-reporter@mozilla.org\":\"b868eb5e-e7cb-495b-89bf-cead9278bebc\",\"webcompat@mozilla.org\":\"a8a35ea7-5164-444f-9ac5-75181af8a968\",\"fxmonitor@mozilla.org\":\"f9096fd7-3ffa-4c79-bec3-399df93d33d9\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1554433139);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190328071059");
user_pref("media.gmp-manager.lastCheck", 1554433139);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "45b642d4-ca58-4c7f-8f23-d7d00acee299");
user_pref("security.sandbox.plugin.tempDirSuffix", "5a05d88c-0309-48bb-b53f-b013b6274c55");
user_pref("services.blocklist.addons.checked", 1554411874);
user_pref("services.blocklist.gfx.checked", 1554411874);
user_pref("services.blocklist.onecrl.checked", 1554411874);
user_pref("services.blocklist.pinning.checked", 1554411874);
user_pref("services.blocklist.plugins.checked", 1554411874);
user_pref("services.settings.clock_skew_seconds", 21558);
user_pref("services.settings.last_update_seconds", 1554411874);
user_pref("services.settings.main.language-dictionaries.last_check", 1554411874);
user_pref("services.settings.main.onboarding.last_check", 1554411874);
user_pref("services.settings.main.sites-classification.last_check", 1554411874);
user_pref("services.settings.main.tippytop.last_check", 1554411874);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1554433038);
user_pref("toolkit.telemetry.cachedClientID", "c50e0eb9-d29a-443b-a5e7-11776433968b");
user_pref("toolkit.telemetry.previousBuildID", "20190328071059");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
